import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TarotProvider } from "@/contexts/TarotContext.context";
import { ResultsProvider } from "@/contexts/ResultsContext.context";
import { HistoryProvider } from "@/contexts/HistoryContext.context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HistoryProvider>
          <TarotProvider>
            <ResultsProvider>
              {children}
            </ResultsProvider>
          </TarotProvider>
        </HistoryProvider>
      </body>
    </html>
  );
}
